# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Generate release PR

on:
  workflow_dispatch:
    inputs: #checkov:skip=CKV_GHA_7
      project:
        type: choice
        description: Project to release
        options:
          - foundry_basic
          - foundry_basic_private
          - foundry_standard
          - foundry_standard_private

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-release-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Changie
        uses: miniscruff/changie-action@5036dffa79ffc007110dc7f75eca7ef72780e147 # v2.1.0
        with:
          version: latest
          args: --version

      - name: Compile Changelog
        id: changelog
        run: |
          changie batch auto --project "${PROJECT}"
          changie merge
          version=$(changie latest --project "${PROJECT}")
          version="${version//$PROJECT/}"
          echo "version=${version}" >>"$GITHUB_OUTPUT"
        env:
          PROJECT: ${{ github.event.inputs.project }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          title: "chore(release): ${{ github.event.inputs.project }}/${{ steps.changelog.outputs.version }}"
          branch: "release/${{ github.event.inputs.project }}-${{ steps.changelog.outputs.version }}"
          commit-message: "chore(release): ${{ github.event.inputs.project }}/${{ steps.changelog.outputs.version }}"
          body-path: "./.changes/${{ github.event.inputs.project }}/${{ steps.changelog.outputs.version }}.md"
