---
name: Prebuilt Devcontainer base

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every sunday
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}-prebuilt-devcontainer-base
  IMAGE_NAME: ${{ github.repository }}-prebuilt-devcontainer

permissions:
  contents: read
  packages: read
  id-token: none

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup devcontainers cli
        run: npm install -g @devcontainers/cli

      - name: Build and push base devcontainer image
        run: |
          # shellcheck disable=SC2086

          lowercase_image_name=$(echo "${{ env.BASE_IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          devcontainer build \
            --workspace-folder . \
            --config ./.devcontainer/local/devcontainer.json \
            --image-name "${{ env.REGISTRY }}/$lowercase_image_name" \
            --platform linux/amd64,linux/arm64 \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max
